### ISSUE TITLE
Activity tree and file tree

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app-admin-panel#11]
We need to organize activities, perhaps by a folder tree, and organize files such as images as well.  Once we have 100 surveys and 100 cognitive assessments, it will become unmanageable.  Likewise, the app's activities view should compress if there are too many as well.

**Comment by shnizzedy** [comment]
Related: https://github.com/ChildMindInstitute/mindlogger-app/issues/54, https://github.com/ChildMindInstitute/mindlogger-app/issues/57

**Comment by binarybottle** [comment]
Currently, we're not looking at many activities within an applet, and they are organized by when they need to get done, so not too concerned.
