### ISSUE TITLE
✨ Response Values in Admin Panel Activity Editor

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#14]
# The Current State of the Editor

Currently the activity editor on the webapp allows users to add/edit response options, but the values those responses are mapped to is opaque and immutable:

![current version](https://user-images.githubusercontent.com/5974438/37838868-656a5c90-2e8f-11e8-8e9f-151ef85cf5c0.png)

# Proposed Update

My idea for adding scoring values to the editor is to bifurcate the text inputs to show the associated values and allow those values to be edited, so the `{text:"abc", value:0.5}` objects in the `rows` arrays would be represented by text on the left (white background), value on the right (gray background):<a name="numericrovs" id="numericrovs"></a>

### numeric response option values

![numeric response option values](https://user-images.githubusercontent.com/5974438/37838970-ad8b5754-2e8f-11e8-9e7b-1e52bd877fe8.png)<a name="textrovs" id="textrovs"></a>

### text response option values

![text response option values](https://user-images.githubusercontent.com/5974438/37839168-29dfd4b0-2e90-11e8-860f-3177abac2f1a.png)

## Default response option values

I think defaulting to match the response text makes sense (like the <a href="#textrovs">text response option values example above</a>), though defaulting to incrementing integers (like the <a href="#numericrovs">numeric response option values example above</a>) could make sense as well. @binarybottle, thoughts?

---

Related ChildMindInstitute/ab2cd-app-backend#17, ChildMindInstitute/ab2cd-app-backend#18

**Comment by binarybottle** [comment]
The panels have been completely redesigned, and the Editor panel is being reengineered from scratch, so closing this issue.
