### ISSUE TITLE
📚 Document Figma Vis-à-Vis Girder

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#15]

**Comment by shnizzedy** [comment]
[Figma (Mindlogger admin panel)](https://www.figma.com/proto/cchWwbmGc7uZwIAzRfxHEJhx)
[Figma Vis à Vis Girder](https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/wiki/Figma-Vis-%C3%A0-Vis-Girder)

**Comment by binarybottle** [comment]
We haven't used Figma for a long time, so closing.
