### ISSUE TITLE
📝 📚 Assign Users to Volumes

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#19]
@binarybottle — @erik-ilyin and/or I will be adding code to assign Volumes to Users ![soon](https://i.kym-cdn.com/entries/icons/original/000/005/673/sooon.jpg).

We already have example code in the [API Examples.js notebook](https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/c70ce46bf495083b5ada0bc1782003292d4da480/mindlogger_backend_dev/API%20Examples.js.ipynb).

If you'd like to design the interface for this function in the admin panel, the race is on!

**Comment by shnizzedy** [comment]
Is [this screen](https://www.figma.com/proto/cchWwbmGc7uZwIAzRfxHEJhx/Mindlogger-Admin-Panel?node-id=79:0) the place?

![Figma node 79:0](https://user-images.githubusercontent.com/5974438/45444313-26139500-b695-11e8-9b3e-6736090d2a92.png)

**Comment by binarybottle** [comment]
Yes!  The Manage Editors and Manage Managers screens both have a right column for adding/removing Volumes (I'll update the text at the top of each of those screens accordingly), and now that we have obliterated assigned User+Volume codes, we can remove the Code column and add a Volume column to this screen as well!

**Comment by shnizzedy** [comment]
@erik-ilyin ― We're [assigning Users to Volumes and not the other way around](https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/issues/19#event-1842349828). I've been uncharacteristically sloppy in using those phrases interchangeably. Does [the current wireframe](https://www.figma.com/proto/cchWwbmGc7uZwIAzRfxHEJhx/Mindlogger-Admin-Panel?node-id=79:0) make sense for [Managers to assign Users to Volumes](https://github.com/ChildMindInstitute/mindlogger-app-backend/wiki/Roles#manager) (adding a User's `_id` to the Volume's metadata `members` object and copying the Volume to the User)?

**Comment by shnizzedy** [comment]
When a User is added to a Volume (in `meta.members.users`), that User should be added as a Viewer of his/her own data (in `meta.members.viewers`) and a Folder for that Volume should be created in that User's `Responses` Folder. That Volume's `meta.meta.members.viewers` should then be checked for additional viewers. For example, in the Volume [`EMA: Parent`](http://mindlogger-girder-atlas.a4vwd5q7ib.us-east-1.elasticbeanstalk.com/#folder/5ba50ca20a76ac049becd54c), the `meta.members` Object is

```json
{
  "editors": [
    "5b4ca32338488311497dc9bc"
  ],
  "managers": [
    "5b4ca32338488311497dc9bc"
  ],
  "owners": [
    "5b4ca32338488311497dc9bc"
  ],
  "users": [
    "5b4ca32338488311497dc9bc"
  ],
  "viewers": [
    {
      "5b4ca32338488311497dc9bc": [
        "5b4ca32338488311497dc9bc"
      ],
      "group/5bab8fc80a76ac049becd5ec": [
        "folder/5ba50ca20a76ac049becd54c.meta.members.users"
      ]
    }
  ]
}
```

So in [User 5b4ca32338488311497dc9bc](http://mindlogger-girder-atlas.a4vwd5q7ib.us-east-1.elasticbeanstalk.com/#user/5b4ca32338488311497dc9bc)'s [`Responses` Folder](http://mindlogger-girder-atlas.a4vwd5q7ib.us-east-1.elasticbeanstalk.com/#folder/5bab8a6b0a76ac049becd5eb), we create an [`EMA: Parent` Folder](http://mindlogger-girder-atlas.a4vwd5q7ib.us-east-1.elasticbeanstalk.com/#folder/5bab97000a76ac049becd5ef) and check its permissions to add any missing viewers.

Step 1: Get current permissions:
```json
{
  "groups": [
    
  ],
  "users": [
    {
      "flags": [
        
      ],
      "id": "5b4ca32338488311497dc9bc",
      "level": 2,
      "login": "clucasjon",
      "name": "Jon Clucas"
    }
  ]
}
```
(just one person with access, myself, the user-as-owner (level 2))

If any other individual Viewers were assigned to this User, we'd need to add them. Since the only individual already has higher-level access, that user stays the same. In this case, we also have a group with permissions to view all Users of this Volume, so we add that group viewer access (level 0):

```json
{
  "groups": [
    {
      "id": "5bab8fc80a76ac049becd5ec",
      "level": 0
    }
  ],
  "users": [
    {
      "flags": [
        
      ],
      "id": "5b4ca32338488311497dc9bc",
      "level": 2,
      "login": "clucasjon",
      "name": "Jon Clucas"
    }
  ]
}
```

In a PUT command, we send the new access rules to the DB:

```rest
PUT /folder/5bab97000a76ac049becd5ef/access access={"groups": [{"id": "5bab8fc80a76ac049becd5ec", "level": 0}], "users": [{"flags": [], "id": "5b4ca32338488311497dc9bc", "level": 2, "login": "clucasjon", "name": "Jon Clucas"}]}
```

# ⚠ IMPORTANT ⚠

**Girder replaces access with this `PUT` call, so each of these `PUT` calls must be carefully constructed to include existing access that should not be modified (eg, the User owning his/her own data).**

If the `PUT` call above was successful, the permissions should now be updated:

```json
{
  "groups": [
    {
      "description": "Individuals associated with the Healthy Brain Network who have blanket access to participant data.",
      "flags": [
        
      ],
      "id": "5bab8fc80a76ac049becd5ec",
      "level": 0,
      "name": "Healthy Brain Network data access"
    }
  ],
  "users": [
    {
      "flags": [
        
      ],
      "id": "5b4ca32338488311497dc9bc",
      "level": 2,
      "login": "clucasjon",
      "name": "Jon Clucas"
    }
  ]
}
```
