### ISSUE TITLE
✨ Previews on Selection Pages

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#24]
On any page in the admin panel where one might select an Activity or Volume, add functionality to pop up a preview modal.

- Activity:
  Page through default screens.
- Volume:
  List Activities (and preview function for these Activities)
- User:
  List Volumes they Edit, Manage, or Own.

**Comment by binarybottle** [comment]
This should take the screen views from the Edit Screens side menu, with a miniature view of the first screen within the modal view with a clickthrough to see subsequent screens.

**Comment by binarybottle** [comment]
The panels have been completely redesigned, and the Editor panel is being reengineered from scratch, so closing this issue.
