### ISSUE TITLE
✨ Checkboxes for Selecting Multiple Activities

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#28]
For the highlighted `⊕` button: ![Selected plus button](https://user-images.githubusercontent.com/5974438/45570810-12516580-b832-11e8-8870-3de4611b6fec.png)

**Comment by binarybottle** [comment]
The panels have been completely redesigned, and the Editor panel is being reengineered from scratch, so closing this issue.
