### ISSUE TITLE
🌑👻 Score Values in Editor

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#36]
Missing feature: Score values for options in Activity editor.

![highlighted current vs wireframe](https://user-images.githubusercontent.com/5974438/46107251-e1195380-c1a8-11e8-9825-264d35c7d8e6.png)

In the image above, the current Activity editor is on the left with the missing score value area highlighted. The wireframe showing what should be there is highlighted on the right.

**Comment by binarybottle** [comment]
The panels have been completely redesigned, and the Editor panel is being reengineered from scratch, so closing this issue.
