### ISSUE TITLE
🎛 Conditional Navigation

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#38]
Conditionally accessible screens don't have a place on the current interface. I think below the default screens in the screen drawer makes sense as a place for them (highlighted in the screenshot below:

![highlighted drawer](https://user-images.githubusercontent.com/5974438/46113524-cb158e00-c1bc-11e8-8510-836ab280c9c7.png)

)

There should be a clear division between the default playlist queue and the extra screens (a color change, a horizontal bar, a header, more than one of these). Also, the y in the "x of y" at the bottom of each screen should be the total in the default queue (the "screens" Array in the Activity Version Folder) and should be the total of all possible screens for the extras, so if there was an Activity with 5 screens in the default queue and 3 extra that are accessible by conditionals, the numbers at the bottom would be

- 1 of 5
- 2 of 5
- 3 of 5
- 4 of 5
- 5 of 5
- 6 of 8
- 7 of 8
- 8 of 8

---

The drawer should be drag-and-drop so screens can be reordered and moved between the playlist queue and the extras section.

---

Related: #37, ChildMindInstitute/mindlogger-app-backend#36

**Comment by shnizzedy** [comment]
Duplicate of ChildMindInstitute/mindlogger-app-backend#36

**Comment by erik-ilyin** [comment]
@shnizzedy We don't have extra screens working so we shouldn't be pushing the unfinished commits to master. please revert the change you made regarding this extra screen feature and make new branch

**Comment by erik-ilyin** [comment]
@shnizzedy Conditionally accessible screens are among those screens in order, if you put number in skip to screen, it skips to target screen and continue, that is how it works as I discussed with @binarybottle. So please revert the change related to this.

**Comment by binarybottle** [comment]
The panels have been completely redesigned, and the Editor panel is being reengineered from scratch, so closing this issue.
