### ISSUE TITLE
🔒 Migrate to Bootstrap 4

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#42]
### [Migrating to v4](https://getbootstrap.com/docs/4.0/migration/)

Ref [⚠ bootstrap](https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/network/alert/package.json/bootstrap/open)

**Comment by shnizzedy** [comment]
Replaces #32

**Comment by binarybottle** [comment]
The panels have been completely redesigned, so closing this issue.
