### ISSUE TITLE
🐛 Off-by-one Skip Screen Entry

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#47]
Ref https://trello.com/c/RbsVONBx

**Comment by shnizzedy** [comment]
> [@shnizzedy This commit bring issues on copying activity sets and adding new screen into activity set. It actually broke relationships between screens and activity. Skip to screen should not be done in this logic. we already have the logic. If there is issue, we need to fix from there.](https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/pull/57#issuecomment-443924408)

Here's a more explicit description of this issue which I resolved in de002e7 and #57:

JavaScript is 0-indexed. The preview drawer in our admin panel is 1-indexed. The issue is the number showing in the "Skip to screen" field. For example, the first screen in [the physical health Activity in the EMA: Parent Activity Set](https://app.mindlogger.info/acts/5bd88558336da80de9145b76/edit) ("Did your child experience any kind of pain today?") should skip to the fourth screen ("How was your child's physical health today?") if skipped.

Here that screen is with this issue in the current admin panel:

![with issue](https://user-images.githubusercontent.com/5974438/49454064-69703200-f7b2-11e8-8e0d-bd0eee190042.png)

Here that same screen is with my fix:

![with fix](https://user-images.githubusercontent.com/5974438/49454160-97ee0d00-f7b2-11e8-9beb-a22b90ef3e3e.png)

It's too confusing for editors to have to remember to subtract one from the numbers in the preview drawer when they enter the skip-to screens.

**Comment by binarybottle** [comment]
The panels are being completely redesigned, so closing this issue.
