### ISSUE TITLE
"Click login for admin panel" when already logged in.

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#75]
![Screen Shot 2018-11-22 at 3.48.23 PM.png](https://trello-attachments.s3.amazonaws.com/5bdca6be9677f381d701cd51/5bf4406d15b9ff3fb98a6a5d/da9dfd283d36caea9df49d64331d351b/Screen_Shot_2018-11-22_at_3.48.23_PM.png)

Ref https://trello.com/c/gDQpvTrp

**Comment by binarybottle** [comment]
The panels are being completely redesigned, so closing this issue.
