### ISSUE TITLE
"Select all" after a search should only select all results, not everyone.

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#80]
![Screen Shot 2018-12-03 at 2.54.37 PM.png](https://trello-attachments.s3.amazonaws.com/5bdca6be9677f381d701cd51/5bdcaaa484bfae403c045a55/9a9e35e3755d9625bd2d2d5f8c3a1d1f/Screen_Shot_2018-12-03_at_2.54.37_PM.png)

![Screen Shot 2018-12-03 at 2.54.53 PM.png](https://trello-attachments.s3.amazonaws.com/5bdca6be9677f381d701cd51/5bdcaaa484bfae403c045a55/36f876c88edb7f87d6b86003a99ed10a/Screen_Shot_2018-12-03_at_2.54.53_PM.png)

![Screen Shot 2018-12-03 at 2.55.03 PM.png](https://trello-attachments.s3.amazonaws.com/5bdca6be9677f381d701cd51/5bdcaaa484bfae403c045a55/417777b57bb4fb1c9963626ed6955e2d/Screen_Shot_2018-12-03_at_2.55.03_PM.png)

Ref https://trello.com/c/kgHW9Di5

**Comment by binarybottle** [comment]
The panels are being completely redesigned, so closing this issue.
