### ISSUE TITLE
gh-pages DNS

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-admin-panel#93]
@binarybottle can you please update the `CNAME` for `app.mindlogger.info` to point to `childmindinstitute.github.io.`? I made some changes to reduce my daily time putting users back into the user list, and I'd like to serve it up on gh-pages and kill the old EC2 we've been running on.

**Comment by binarybottle** [comment]
Subsumed by a new issue and new domain!

**Comment by shnizzedy** [comment]
duplicate of https://github.com/ChildMindInstitute/matter-website/issues/148

**Comment by shnizzedy** [comment]
app.mindlogger.org was was redirecting to https://app.mindlogger.info, but that appears to be totally dead now. 

> @binarybottle can you please update the CNAME for ~app.mindlogger.info~ <sub>^</sub><sup>app.mindlogger.org</sup> to point to childmindinstitute.github.io.?

Related, https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/issues/93 https://github.com/ChildMindInstitute/matter-website/issues/148

**Comment by binarybottle** [comment]
Done!

**Comment by shnizzedy** [comment]
![thank you](https://user-images.githubusercontent.com/5974438/62247866-c27d7d80-b3b4-11e9-8ba4-16b9b8625541.png)
